/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import carrental.DB_Con;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.*;


/**
 *
 * @author Yusra
 */
public class CarAdd extends javax.swing.JFrame {

    Connection conn = null;
    PreparedStatement pst=null;
    ResultSet rs = null;
    
    public CarAdd() {
        initComponents();
        
        //DB connection
        conn = DB_Con.connect();
    }
        private void getID(){
        try {
            rs = pst.executeQuery("SELECT MAX(CarID) AS CarID FROM Car");
            int lastid = rs.getInt("CarID");
        } catch (Exception e) {
            System.out.println(e);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        makeinput = new javax.swing.JTextField();
        modelinput = new javax.swing.JTextField();
        yearinput = new javax.swing.JTextField();
        seatsinput = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cartypeselect = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 500));
        setResizable(false);

        jPanel1.setPreferredSize(new java.awt.Dimension(800, 500));
        jPanel1.setLayout(null);

        makeinput.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        makeinput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                makeinputActionPerformed(evt);
            }
        });
        jPanel1.add(makeinput);
        makeinput.setBounds(410, 180, 220, 30);

        modelinput.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        modelinput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modelinputActionPerformed(evt);
            }
        });
        jPanel1.add(modelinput);
        modelinput.setBounds(410, 220, 220, 30);

        yearinput.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jPanel1.add(yearinput);
        yearinput.setBounds(410, 260, 220, 30);

        seatsinput.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jPanel1.add(seatsinput);
        seatsinput.setBounds(410, 300, 220, 30);

        jButton1.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/icons/dollar32.png"))); // NOI18N
        jButton1.setText("Add Prices");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(410, 340, 160, 41);

        jButton2.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/icons/home.png"))); // NOI18N
        jButton2.setText("Home");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(660, 20, 130, 50);

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel7.setText("Car type                :");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(270, 140, 140, 30);

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel6.setText("Number of seats  :");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(270, 300, 130, 30);

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel5.setText("Year                      :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(270, 260, 130, 30);

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel4.setText("Model                    :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(270, 220, 130, 30);

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel3.setText("Make                     :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(270, 180, 140, 30);

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel2.setText("                                     ADD CAR");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 80, 820, 51);

        cartypeselect.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        cartypeselect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Luxury", "Limousine", "Normal", "Wagons" }));
        jPanel1.add(cartypeselect);
        cartypeselect.setBounds(410, 140, 220, 30);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/bac.jpeg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 820, 510);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 821, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(826, 539));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String carType = cartypeselect.getSelectedItem().toString();
        String make = makeinput.getText();
        String model = modelinput.getText();
        String year = yearinput.getText();
        String seats = seatsinput.getText();
        
    if (!year.matches("[0-9]+")) {
            JOptionPane.showMessageDialog(null, "Invalid Year");
        }    
    
        try{
            String addQuery = "INSERT INTO car(Make,Model,Year,Seats,CarType) values ('"+make+"','"+model+"','"+year+"','"+seats+"','"+carType+"')";
            pst = conn.prepareStatement(addQuery);
            pst.execute();
           }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        
        AddPrice prc =   new AddPrice();
        prc.setVisible(true);
//        this.dispose();
        
    }//GEN-LAST:event_jButton1ActionPerformed
    

    private void makeinputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_makeinputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_makeinputActionPerformed

    private void modelinputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modelinputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modelinputActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        ManagerHome home =   new ManagerHome();
        home.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CarAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CarAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CarAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CarAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CarAdd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cartypeselect;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField makeinput;
    private javax.swing.JTextField modelinput;
    private javax.swing.JTextField seatsinput;
    private javax.swing.JTextField yearinput;
    // End of variables declaration//GEN-END:variables
}
