/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import carrental.DB_Con;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;

/**
 *
 * @author Yusra
 */
public class updatePrices extends javax.swing.JFrame {
    Connection conn = null;
    PreparedStatement abc =null;
    ResultSet rs = null;
    /**
     * Creates new form updatePrices
     */
    public updatePrices() 
    {
        initComponents();
        //DB connection
        conn = DB_Con.connect();
        
        try 
        { 
            Statement st = conn.createStatement();
            String fillQuery = "SELECT DISTINCT(car.Make),car.Model FROM car";
            rs = st.executeQuery(fillQuery);
           
            while (rs.next()) 
            {
                  jComboBox1.addItem(rs.getString("Make"));  
                  jComboBox2.addItem(rs.getString("Model"));
            }         
        } 
        catch (Exception e) 
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        overdueupdate = new javax.swing.JTextField();
        refundableupdate = new javax.swing.JTextField();
        priceupdate = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(null);

        jButton1.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/icons/home.png"))); // NOI18N
        jButton1.setText("Home");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(670, 20, 115, 50);

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel4.setText("                              UPDATE PRICES");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(0, 90, 820, 51);

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/icons/new.png"))); // NOI18N
        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(380, 330, 125, 41);

        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel8.setText("Price per hour             :");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(210, 210, 160, 30);

        jLabel9.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel9.setText("Refundable deposit    :");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(210, 250, 160, 30);

        jLabel10.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel10.setText("Overdue amount         :");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(210, 290, 150, 30);

        overdueupdate.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        overdueupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                overdueupdateActionPerformed(evt);
            }
        });
        jPanel1.add(overdueupdate);
        overdueupdate.setBounds(380, 290, 220, 27);

        refundableupdate.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        refundableupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refundableupdateActionPerformed(evt);
            }
        });
        jPanel1.add(refundableupdate);
        refundableupdate.setBounds(380, 250, 220, 27);

        priceupdate.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jPanel1.add(priceupdate);
        priceupdate.setBounds(380, 210, 220, 30);

        jComboBox1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Make" }));
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(380, 160, 150, 30);

        jComboBox2.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Model" }));
        jPanel1.add(jComboBox2);
        jComboBox2.setBounds(540, 160, 150, 30);

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel3.setText("Select Car                  :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(210, 160, 150, 30);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/bac.jpeg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 820, 510);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 810, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(826, 539));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ManagerHome home =   new ManagerHome();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void overdueupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_overdueupdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_overdueupdateActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         
         String price = priceupdate.getText();
         String refund = refundableupdate.getText();
         String overdue = overdueupdate.getText();
         String selectMake = jComboBox1.getSelectedItem().toString();
         String selectModel = jComboBox2.getSelectedItem().toString();
       
         try
         {
            Statement st = conn.createStatement();
            String getID = "SELECT carID FROM car WHERE Make='"+selectMake+"' and Model='"+selectModel+"' ";
            ResultSet rst  = st.executeQuery(getID);
             
            while (rst.next()) 
            {
                int car = rst.getInt("CarID");
                String update_price = "UPDATE price SET AmountPerHour="+price+",Refundable="+refund+",Overdue="+overdue+" where CarID = "+car+" ";
                abc = conn.prepareStatement(update_price);
                abc.execute();         
            }
          }
        catch(Exception e)
        {
            System.out.println(e);
            JOptionPane.showMessageDialog(null,e);
        }
         
        ManagerHome home =   new ManagerHome();
        home.setVisible(true);
        this.dispose();
         
    }//GEN-LAST:event_jButton2ActionPerformed

    private void refundableupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refundableupdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_refundableupdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(updatePrices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(updatePrices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(updatePrices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(updatePrices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new updatePrices().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField overdueupdate;
    private javax.swing.JTextField priceupdate;
    private javax.swing.JTextField refundableupdate;
    // End of variables declaration//GEN-END:variables
}
