/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UIPkg;

import DBCon.DBConnection;
import Validations.ValidateMe;
import java.awt.Color;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author Ihsan Izwer
 */
public class AddUser extends javax.swing.JFrame {

    /**
     * Creates new form AddUser
     * 
     */
    
    DBConnection db;
    public AddUser() {
       
        initComponents();
        this.setLocationRelativeTo(null);
        this.setSize(820, 512);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLbl = new javax.swing.JLabel();
        nameLbl = new javax.swing.JLabel();
        uNameTxt = new javax.swing.JTextField();
        permissionLbl = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        nameTxt = new javax.swing.JTextField();
        pwdTxt = new javax.swing.JTextField();
        addUserBtn = new javax.swing.JButton();
        closeBtn = new javax.swing.JButton();
        usrLbl = new javax.swing.JLabel();
        pwdLbl = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        titleLbl.setFont(new java.awt.Font("Comic Sans MS", 0, 36)); // NOI18N
        titleLbl.setText("Add User");
        getContentPane().add(titleLbl);
        titleLbl.setBounds(10, 10, 190, 70);

        nameLbl.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        nameLbl.setText("Name :");
        getContentPane().add(nameLbl);
        nameLbl.setBounds(280, 150, 100, 50);

        uNameTxt.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        getContentPane().add(uNameTxt);
        uNameTxt.setBounds(380, 100, 280, 30);

        permissionLbl.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        permissionLbl.setText("Permissions:");
        getContentPane().add(permissionLbl);
        permissionLbl.setBounds(220, 270, 160, 60);

        jComboBox1.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "admin", "manager", "receptionist" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(380, 290, 280, 30);

        nameTxt.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        getContentPane().add(nameTxt);
        nameTxt.setBounds(380, 160, 280, 30);

        pwdTxt.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        getContentPane().add(pwdTxt);
        pwdTxt.setBounds(380, 220, 280, 30);

        addUserBtn.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        addUserBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/icons/Material Icons_e7f0(0)_64.png"))); // NOI18N
        addUserBtn.setText("Add User");
        addUserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addUserBtnActionPerformed(evt);
            }
        });
        getContentPane().add(addUserBtn);
        addUserBtn.setBounds(360, 350, 210, 70);

        closeBtn.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        closeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/icons/x-mark-32.png"))); // NOI18N
        closeBtn.setText("Close");
        closeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBtnActionPerformed(evt);
            }
        });
        getContentPane().add(closeBtn);
        closeBtn.setBounds(670, 20, 120, 40);

        usrLbl.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        usrLbl.setText("Username (unique) :");
        getContentPane().add(usrLbl);
        usrLbl.setBounds(140, 90, 240, 50);

        pwdLbl.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        pwdLbl.setText("Password:");
        getContentPane().add(pwdLbl);
        pwdLbl.setBounds(250, 220, 130, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/bac.jpeg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(4, -6, 820, 520);

        setBounds(0, 0, 836, 551);
    }// </editor-fold>//GEN-END:initComponents

    private void addUserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addUserBtnActionPerformed
          String username = uNameTxt.getText();
        String name =nameTxt.getText();
        String password = pwdTxt.getText();
        String permissions = jComboBox1.getSelectedItem().toString();
        db = new DBConnection();
       

        ValidateMe vm = new ValidateMe(username, password, name, permissions);
        if(vm.isValidAdduser()==true){
             if(db.addUser(username, password, name, permissions)==true){
             JOptionPane.showMessageDialog(this, "User added successfully!");
             uNameTxt.setText("");
             nameTxt.setText("");
             pwdTxt.setText("");
             jComboBox1.setSelectedIndex(0);
        }
        }
    }//GEN-LAST:event_addUserBtnActionPerformed

    private void closeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBtnActionPerformed
        new AdminScreen().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_closeBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addUserBtn;
    private javax.swing.JButton closeBtn;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel nameLbl;
    private javax.swing.JTextField nameTxt;
    private javax.swing.JLabel permissionLbl;
    private javax.swing.JLabel pwdLbl;
    private javax.swing.JTextField pwdTxt;
    private javax.swing.JLabel titleLbl;
    private javax.swing.JTextField uNameTxt;
    private javax.swing.JLabel usrLbl;
    // End of variables declaration//GEN-END:variables
}
