/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UIPkg;

import DBCon.DBConnection;
import Validations.ValidateMe;
import java.awt.Color;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.*;


/**
 *
 * @author Mohamed Ihsan Izwer
 */
public class AdminScreen extends javax.swing.JFrame {

    /**
     * Creates new form AdminScreen
     */
    public AdminScreen() {
        
        initComponents();
        this.setLocationRelativeTo(null);
        this.setSize(820, 512);
        DBConnection db = new DBConnection("SELECT username, name, permissions FROM users", 1);
       
        usrTable.setModel(DbUtils.resultSetToTableModel( db.getRS()));
        db.closeCon();

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("carr?autoReconnect=true&useSSL=falsePU").createEntityManager();
        usersQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT u FROM Users u");
        usersList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : usersQuery.getResultList();
        titleLbl = new javax.swing.JLabel();
        logOutBtn = new javax.swing.JButton();
        changePwdBtn = new javax.swing.JButton();
        addUsrBtn = new javax.swing.JButton();
        updateUserBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        usrTable = new javax.swing.JTable();
        deleteBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        titleLbl.setFont(new java.awt.Font("Comic Sans MS", 0, 36)); // NOI18N
        titleLbl.setText("Admin Dashboard");
        getContentPane().add(titleLbl);
        titleLbl.setBounds(10, 10, 380, 50);

        logOutBtn.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        logOutBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/icons/x-mark-32.png"))); // NOI18N
        logOutBtn.setText("Log out");
        logOutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutBtnActionPerformed(evt);
            }
        });
        getContentPane().add(logOutBtn);
        logOutBtn.setBounds(670, 10, 130, 40);

        changePwdBtn.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        changePwdBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/icons/order32.png"))); // NOI18N
        changePwdBtn.setText("Change Password");
        changePwdBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePwdBtnActionPerformed(evt);
            }
        });
        getContentPane().add(changePwdBtn);
        changePwdBtn.setBounds(620, 80, 177, 41);

        addUsrBtn.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        addUsrBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/icons/Material Icons_e7f0(0)_64.png"))); // NOI18N
        addUsrBtn.setText("Add User");
        addUsrBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addUsrBtnActionPerformed(evt);
            }
        });
        getContentPane().add(addUsrBtn);
        addUsrBtn.setBounds(610, 150, 190, 70);

        updateUserBtn.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        updateUserBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/icons/Material Icons_e7fe(0)_64.png"))); // NOI18N
        updateUserBtn.setText("Update user");
        updateUserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateUserBtnActionPerformed(evt);
            }
        });
        getContentPane().add(updateUserBtn);
        updateUserBtn.setBounds(610, 250, 190, 70);

        usrTable.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        usrTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(usrTable);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(100, 80, 480, 340);

        deleteBtn.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        deleteBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/icons/Material Icons_e5c9(0)_64.png"))); // NOI18N
        deleteBtn.setText("Delete user");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });
        getContentPane().add(deleteBtn);
        deleteBtn.setBounds(610, 350, 180, 70);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/bac.jpeg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, -10, 820, 520);

        setSize(new java.awt.Dimension(836, 551));
    }// </editor-fold>//GEN-END:initComponents

    private void logOutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutBtnActionPerformed
         LState.setLUser(null);
        new LogInScreen().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logOutBtnActionPerformed

    private void changePwdBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePwdBtnActionPerformed
           JPasswordField pwd = new JPasswordField();
    int choice = JOptionPane.showConfirmDialog(null, pwd, "Enter the new Password :", JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);
        if (choice == JOptionPane.OK_OPTION) {
          String newPwd = new String(pwd.getPassword());
          ValidateMe v = new ValidateMe();
          if(v.isValidPassword(newPwd)){
              JPasswordField pwd2 = new JPasswordField();
              int choice2 = JOptionPane.showConfirmDialog(null, pwd2, "Retype the new Password :", JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);
               if(choice2== JOptionPane.OK_OPTION){
                   if(new String(pwd2.getPassword()).equals(newPwd)){
                       DBConnection db = new DBConnection("UPDATE users SET password ='"+newPwd+"' WHERE username LIKE '"+LState.getLUser()+"'", 2);
                       JOptionPane.showMessageDialog(null, "Password was changed successfully!");
                       db.closeCon();
                   }else{
                       JOptionPane.showMessageDialog(null, "The passwords you entered did not match. Please try again.");
                   }
               }else{
                   JOptionPane.showMessageDialog(null, "Password was not changed!");
               }
          }
        }
    }//GEN-LAST:event_changePwdBtnActionPerformed

    private void addUsrBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addUsrBtnActionPerformed
          new AddUser().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_addUsrBtnActionPerformed

    private void updateUserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateUserBtnActionPerformed
         new UpdateUser().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_updateUserBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        new DeleteUser().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_deleteBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               
                
                new AdminScreen().setVisible(true);
                
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addUsrBtn;
    private javax.swing.JButton changePwdBtn;
    private javax.swing.JButton deleteBtn;
    private javax.persistence.EntityManager entityManager;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton logOutBtn;
    private javax.swing.JLabel titleLbl;
    private javax.swing.JButton updateUserBtn;
    private java.util.List<UIPkg.Users> usersList;
    private javax.persistence.Query usersQuery;
    private javax.swing.JTable usrTable;
    // End of variables declaration//GEN-END:variables
}
