/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UIPkg;

/**
 *
 * @author Ihsan Izwer
 */

import DBCon.DBConnection;
import java.awt.Color;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class DeleteUser extends javax.swing.JFrame {

    /**
     * Creates new form DeleteUser
     */
    
    private Vector usernames;
    
    public DeleteUser() {
        
        initComponents();
        this.setLocationRelativeTo(null);
        
        this.setSize(820, 512);
        usernames = new Vector();
        
        DBConnection db = new DBConnection("SELECT * FROM users;",1);
        ResultSet rs = db.getRS();
        int i =0;
       
        try {
            while(rs.next()){
                usernames.add(i,rs.getNString("username"));
                usrCmb.addItem(usernames.get(i)+" | "+rs.getNString("name")+" | "+rs.getNString("permissions")); 
                i++;
            }
             
            db.closeCon();

        } catch (SQLException ex) {
            Logger.getLogger(UpdateUser.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        selectUserLbl = new javax.swing.JLabel();
        adminPwdLbl = new javax.swing.JLabel();
        titleLbl = new javax.swing.JLabel();
        pwdField = new javax.swing.JPasswordField();
        usrCmb = new javax.swing.JComboBox<>();
        closeBtn = new javax.swing.JButton();
        deleteUsrBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        selectUserLbl.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        selectUserLbl.setText("Select user to be deleted :");
        getContentPane().add(selectUserLbl);
        selectUserLbl.setBounds(60, 150, 320, 50);

        adminPwdLbl.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        adminPwdLbl.setText("Enter Admin password :");
        getContentPane().add(adminPwdLbl);
        adminPwdLbl.setBounds(90, 230, 300, 60);

        titleLbl.setFont(new java.awt.Font("Comic Sans MS", 0, 36)); // NOI18N
        titleLbl.setText("Delete User");
        getContentPane().add(titleLbl);
        titleLbl.setBounds(10, 10, 320, 70);

        pwdField.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        pwdField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwdFieldActionPerformed(evt);
            }
        });
        getContentPane().add(pwdField);
        pwdField.setBounds(400, 240, 370, 40);

        usrCmb.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        getContentPane().add(usrCmb);
        usrCmb.setBounds(400, 150, 360, 40);

        closeBtn.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        closeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/icons/x-mark-32.png"))); // NOI18N
        closeBtn.setText("Close");
        closeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBtnActionPerformed(evt);
            }
        });
        getContentPane().add(closeBtn);
        closeBtn.setBounds(670, 20, 120, 40);

        deleteUsrBtn.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        deleteUsrBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/icons/Material Icons_e5c9(0)_64.png"))); // NOI18N
        deleteUsrBtn.setText("Delete user");
        deleteUsrBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteUsrBtnActionPerformed(evt);
            }
        });
        getContentPane().add(deleteUsrBtn);
        deleteUsrBtn.setBounds(530, 340, 230, 70);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/bac.jpeg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(4, -6, 820, 520);

        setBounds(0, 0, 836, 551);
    }// </editor-fold>//GEN-END:initComponents

    private void pwdFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwdFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwdFieldActionPerformed

    private void deleteUsrBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteUsrBtnActionPerformed
        DBConnection db = new DBConnection();
        if(db.isValidLogin("Admin", new String(pwdField.getPassword()))){
            db = new DBConnection("DELETE FROM users WHERE username LIKE '"+usernames.get(usrCmb.getSelectedIndex())+"'", 2);
            db.closeCon();
            JOptionPane.showMessageDialog(null, usernames.get(usrCmb.getSelectedIndex())+" was deleted!");
            
            usrCmb.removeAllItems();
            pwdField.setText("");
            DBConnection d = new DBConnection("SELECT * FROM users;",1);
            ResultSet rs = d.getRS();
            int i =0;
       
            try {
             while(rs.next()){
                usernames.add(i,rs.getNString("username"));
                usrCmb.addItem(usernames.get(i)+" | "+rs.getNString("name")+" | "+rs.getNString("permissions")); 
                i++;
            }
             
            db.closeCon();
            d.closeCon();

        } catch (SQLException ex) {
            Logger.getLogger(UpdateUser.class.getName()).log(Level.SEVERE, null, ex);
        }
        }else{
            JOptionPane.showMessageDialog(null, "Incorrect password!");
            pwdField.setText("");
            
        }
    }//GEN-LAST:event_deleteUsrBtnActionPerformed

    private void closeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBtnActionPerformed
        new AdminScreen().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_closeBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeleteUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeleteUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeleteUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeleteUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeleteUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adminPwdLbl;
    private javax.swing.JButton closeBtn;
    private javax.swing.JButton deleteUsrBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField pwdField;
    private javax.swing.JLabel selectUserLbl;
    private javax.swing.JLabel titleLbl;
    private javax.swing.JComboBox<String> usrCmb;
    // End of variables declaration//GEN-END:variables
}
