package UIPkg;


import java.awt.Color;
import java.awt.Container;
import DBCon.DBConnection;
import java.awt.Frame;
import java.awt.Toolkit;
import report.RView;
import report.ViewReports;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mohamed Ihsan Izwer
 */
public class LogInScreen extends javax.swing.JFrame {

    /**
     * Creates new form LogInScreen
     */
    DBConnection db = new DBConnection();
   // static LogInScreen l1;
    
    public LogInScreen() {
   
        initComponents();
       
        this.setSize(820, 512);
        this.setLocationRelativeTo(null);

       errLbl.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pwdLbl = new javax.swing.JLabel();
        titleLbl = new javax.swing.JLabel();
        usrTxt = new javax.swing.JTextField();
        logInBtn = new javax.swing.JButton();
        guestBtn = new javax.swing.JButton();
        orLbl = new javax.swing.JLabel();
        usrLbl = new javax.swing.JLabel();
        errLbl = new javax.swing.JLabel();
        pwdTxt = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Log in to Your Key rent a car");
        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(255, 255, 255));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        pwdLbl.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        pwdLbl.setText("Password :");
        getContentPane().add(pwdLbl);
        pwdLbl.setBounds(40, 280, 110, 60);

        titleLbl.setBackground(new java.awt.Color(255, 255, 255));
        titleLbl.setFont(new java.awt.Font("Comic Sans MS", 0, 56)); // NOI18N
        titleLbl.setText("Log In");
        getContentPane().add(titleLbl);
        titleLbl.setBounds(20, 0, 190, 79);

        usrTxt.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        usrTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usrTxtActionPerformed(evt);
            }
        });
        getContentPane().add(usrTxt);
        usrTxt.setBounds(150, 230, 270, 40);

        logInBtn.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        logInBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/icons/linecons_e008(0)_64.png"))); // NOI18N
        logInBtn.setText("Log In");
        logInBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logInBtnActionPerformed(evt);
            }
        });
        getContentPane().add(logInBtn);
        logInBtn.setBounds(200, 350, 180, 70);

        guestBtn.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        guestBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/icons/Entypo_d83d(0)_64.png"))); // NOI18N
        guestBtn.setText("View as guest");
        guestBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guestBtnActionPerformed(evt);
            }
        });
        getContentPane().add(guestBtn);
        guestBtn.setBounds(520, 240, 251, 70);

        orLbl.setFont(new java.awt.Font("Comic Sans MS", 0, 36)); // NOI18N
        orLbl.setText("Or");
        getContentPane().add(orLbl);
        orLbl.setBounds(640, 180, 60, 50);

        usrLbl.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        usrLbl.setText("Username : ");
        getContentPane().add(usrLbl);
        usrLbl.setBounds(20, 230, 140, 40);

        errLbl.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        errLbl.setForeground(new java.awt.Color(255, 0, 0));
        errLbl.setText("Invalid login credentials!");
        getContentPane().add(errLbl);
        errLbl.setBounds(10, 110, 530, 50);

        pwdTxt.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        pwdTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwdTxtActionPerformed(evt);
            }
        });
        getContentPane().add(pwdTxt);
        pwdTxt.setBounds(150, 290, 270, 40);

        jButton1.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/icons/octicons_f006(0)_64.png"))); // NOI18N
        jButton1.setText("View Reports");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(520, 340, 250, 70);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/Picture1.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(4, -6, 820, 520);

        setBounds(0, 0, 836, 553);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // ;; add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void usrTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usrTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usrTxtActionPerformed

    private void pwdTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwdTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwdTxtActionPerformed

    private void logInBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logInBtnActionPerformed
        String user = usrTxt.getText();
        String password = new String(pwdTxt.getPassword());
        
        if((db.isValidLogin(user, password))==false){
            usrTxt.setText("");
            pwdTxt.setText("");
            errLbl.setVisible(true);
        }else{
            errLbl.setVisible(false);
            LState.setLUser(user);
            
            if(db.getUser(user).equals("admin")){
                new AdminScreen().setVisible(true);
                this.dispose();
            }
            else if(db.getUser(user).equals("receptionist")){
                new ReceptionistScreen().setVisible(true);
                this.dispose();
            }
            else{
              new ManagerScreen().setVisible(true);
                this.dispose();
            }
        }
    }//GEN-LAST:event_logInBtnActionPerformed

    private void guestBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guestBtnActionPerformed
        new GuestView().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_guestBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new ViewReports().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogInScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogInScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogInScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogInScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>  
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                try{
                    Thread.sleep(5000);
                    
                }catch(Exception e){
                
                }
                
                new LogInScreen().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel errLbl;
    private javax.swing.JButton guestBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton logInBtn;
    private javax.swing.JLabel orLbl;
    private javax.swing.JLabel pwdLbl;
    private javax.swing.JPasswordField pwdTxt;
    private javax.swing.JLabel titleLbl;
    private javax.swing.JLabel usrLbl;
    private javax.swing.JTextField usrTxt;
    // End of variables declaration//GEN-END:variables
}
