/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UIPkg;

import DBCon.DBConnection;
import Validations.ValidateMe;
import interfaces.CarAdd;
import interfaces.addDeco;
import interfaces.removeCar;
import interfaces.removeDeco;
import interfaces.updatePrices;
import interfaces.viewTables;
import java.awt.Color;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
/**
 *
 * @author Ihsan Izwer
 */
public class ManagerScreen extends javax.swing.JFrame {

    /**
     * Creates new form ManagerScreen
     */
    public ManagerScreen() {
        initComponents();
        this.setSize(820, 512);
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("carr?autoReconnect=true&useSSL=falsePU").createEntityManager();
        usersQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT u FROM Users u");
        usersList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : usersQuery.getResultList();
        closeBtn = new javax.swing.JButton();
        changePwdBtn = new javax.swing.JButton();
        titleLbl = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        closeBtn.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        closeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/icons/out.png"))); // NOI18N
        closeBtn.setText("Log out");
        closeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBtnActionPerformed(evt);
            }
        });
        getContentPane().add(closeBtn);
        closeBtn.setBounds(680, 30, 130, 40);

        changePwdBtn.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        changePwdBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/icons/new.png"))); // NOI18N
        changePwdBtn.setText("Change Password");
        changePwdBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePwdBtnActionPerformed(evt);
            }
        });
        getContentPane().add(changePwdBtn);
        changePwdBtn.setBounds(500, 30, 177, 41);

        titleLbl.setFont(new java.awt.Font("Comic Sans MS", 0, 34)); // NOI18N
        titleLbl.setText("Manager's Dashboard");
        titleLbl.setToolTipText("");
        getContentPane().add(titleLbl);
        titleLbl.setBounds(250, 80, 410, 50);

        jButton4.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/icons/Material Icons_e42a(0)_64.png"))); // NOI18N
        jButton4.setText("VIEW DETAILS");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(70, 150, 240, 90);

        jButton1.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/icons/Material Icons_e531(0)_64.png"))); // NOI18N
        jButton1.setText("ADD CAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(330, 150, 180, 80);

        jButton5.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/icons/frfferge.png"))); // NOI18N
        jButton5.setText("UPDATE PRICES");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(530, 150, 250, 80);

        jButton6.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/icons/icomoon_e697(0)_64.png"))); // NOI18N
        jButton6.setText("ADD DECORATION PACKAGE");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(430, 240, 360, 90);

        jButton2.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/icons/Material Icons_e5c9(0)_64.png"))); // NOI18N
        jButton2.setText("REMOVER  CAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(160, 250, 240, 80);

        jButton8.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/icons/bkgfuegriu ehfekurf.png"))); // NOI18N
        jButton8.setText("REMOVE DECORATION PACKAGE");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8);
        jButton8.setBounds(270, 340, 390, 80);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/bac.jpeg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(4, -6, 820, 520);

        setBounds(0, 0, 836, 551);
    }// </editor-fold>//GEN-END:initComponents

    private void closeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBtnActionPerformed
        LState.setLUser(null);
        new LogInScreen().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_closeBtnActionPerformed

    private void changePwdBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePwdBtnActionPerformed
        JPasswordField pwd = new JPasswordField();
        int choice = JOptionPane.showConfirmDialog(null, pwd, "Enter the new Password :", JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);
        if (choice == JOptionPane.OK_OPTION) {
            String newPwd = new String(pwd.getPassword());
            ValidateMe v = new ValidateMe();
            if(v.isValidPassword(newPwd)){
                JPasswordField pwd2 = new JPasswordField();
                int choice2 = JOptionPane.showConfirmDialog(null, pwd2, "Retype the new Password :", JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);
                if(choice2== JOptionPane.OK_OPTION){
                    if(new String(pwd2.getPassword()).equals(newPwd)){
                        DBConnection db = new DBConnection("UPDATE users SET password ='"+newPwd+"' WHERE username LIKE '"+LState.getLUser()+"'", 2);
                        JOptionPane.showMessageDialog(null, "Password was changed successfully!");
                        db.closeCon();
                    }else{
                        JOptionPane.showMessageDialog(null, "The passwords you entered did not match. Please try again.");
                    }
                }else{
                    JOptionPane.showMessageDialog(null, "Password was not changed!");
                }
            }
        }
    }//GEN-LAST:event_changePwdBtnActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        viewTables table =   new viewTables();
        table.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        CarAdd newCar =   new CarAdd();
        newCar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        updatePrices updatePr =   new updatePrices();
        updatePr.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        addDeco newDeco =   new addDeco();
        newDeco.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        removeCar rCar =   new removeCar();
        rCar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        removeDeco rDeco =   new removeDeco();
        rDeco.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagerScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagerScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagerScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagerScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManagerScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton changePwdBtn;
    private javax.swing.JButton closeBtn;
    private javax.persistence.EntityManager entityManager;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel titleLbl;
    private java.util.List<UIPkg.Users> usersList;
    private javax.persistence.Query usersQuery;
    // End of variables declaration//GEN-END:variables
}
