/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UIPkg;

import DBCon.DBConnection;
import Validations.ValidateMe;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
/**
 *
 * @author Ihsan Izwer
 */


public class VCars extends javax.swing.JFrame {

    /**
     * Creates new form VCars
     */
    
       private String carType;
    private String res ="";
    Vector selectedCars;
    Vector carIDs;
    private int current = 0;
    public VCars() {
           initComponents();
        carIDs = new Vector();
        carType = cTypeCmb.getSelectedItem().toString();
        this.setSize(820, 512);
        this.setLocationRelativeTo(null);
        imgLbl.setVisible(false);
        prevBtn.setVisible(false);
        nextBtn.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLbl = new javax.swing.JLabel();
        noOfSeatTxt = new javax.swing.JTextField();
        cTypeCmb = new javax.swing.JComboBox<>();
        searchBtn = new javax.swing.JButton();
        imgLbl = new javax.swing.JLabel();
        nextBtn = new javax.swing.JButton();
        closeBtn = new javax.swing.JButton();
        prevBtn = new javax.swing.JButton();
        seatsLbl = new javax.swing.JLabel();
        typeLbl = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        titleLbl.setFont(new java.awt.Font("Comic Sans MS", 0, 36)); // NOI18N
        titleLbl.setText("Search cars");
        getContentPane().add(titleLbl);
        titleLbl.setBounds(10, 20, 210, 40);

        noOfSeatTxt.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        noOfSeatTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noOfSeatTxtActionPerformed(evt);
            }
        });
        getContentPane().add(noOfSeatTxt);
        noOfSeatTxt.setBounds(240, 90, 135, 30);

        cTypeCmb.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        cTypeCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Luxury", "Limousine", "Normal", "Wagons" }));
        cTypeCmb.setName(""); // NOI18N
        cTypeCmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cTypeCmbActionPerformed(evt);
            }
        });
        getContentPane().add(cTypeCmb);
        cTypeCmb.setBounds(520, 90, 130, 30);

        searchBtn.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        searchBtn.setText("Search");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });
        getContentPane().add(searchBtn);
        searchBtn.setBounds(710, 90, 90, 30);
        getContentPane().add(imgLbl);
        imgLbl.setBounds(230, 180, 320, 240);

        nextBtn.setText(">");
        nextBtn.setEnabled(false);
        nextBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextBtnActionPerformed(evt);
            }
        });
        getContentPane().add(nextBtn);
        nextBtn.setBounds(680, 280, 41, 60);

        closeBtn.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        closeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/icons/x-mark-32.png"))); // NOI18N
        closeBtn.setText("Close");
        closeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBtnActionPerformed(evt);
            }
        });
        getContentPane().add(closeBtn);
        closeBtn.setBounds(670, 20, 120, 40);

        prevBtn.setText("<");
        prevBtn.setEnabled(false);
        prevBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prevBtnActionPerformed(evt);
            }
        });
        getContentPane().add(prevBtn);
        prevBtn.setBounds(20, 270, 41, 60);

        seatsLbl.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        seatsLbl.setText("Enter number of seats :");
        getContentPane().add(seatsLbl);
        seatsLbl.setBounds(70, 90, 170, 20);

        typeLbl.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        typeLbl.setText("Select car type :");
        getContentPane().add(typeLbl);
        typeLbl.setBounds(400, 90, 110, 20);

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(110, 140, 610, 30);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/bac.jpeg"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(4, -6, 820, 520);

        setBounds(0, 0, 836, 551);
    }// </editor-fold>//GEN-END:initComponents

    private void noOfSeatTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noOfSeatTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noOfSeatTxtActionPerformed

    private void cTypeCmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cTypeCmbActionPerformed
        this.carType = cTypeCmb.getSelectedItem().toString();
    }//GEN-LAST:event_cTypeCmbActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        selectedCars = new Vector();
        current=0;
        String seats = noOfSeatTxt.getText();
        ValidateMe v = new ValidateMe();
        int nSeats = 0;
        if(v.isValidNoSeats(seats)){
            nSeats = Integer.parseInt(seats);
        }

        DBConnection db = new DBConnection("SELECT * FROM car WHERE Seats LIKE '"+nSeats+"' AND CarType LIKE '"+carType+"'",1);
        ResultSet rs = db.getRS();
        try {
            int i = 1;
            while(rs.next()){
                res = res+Integer.toString(i)+". ";
                carIDs.add(i-1,Integer.toString(rs.getInt("CarID")));
                res = res+rs.getString("Model")+" ";
                res = res+rs.getString("Make")+" ";
                res = res+rs.getString("Year")+" ";
                if(rs.getBoolean("Taken"))
                res = res + "   Availability : Unavailable";
                else
                res = res + "   Availability : Available";
                selectedCars.add(i-1, res);
                res="";
                i++;
            }

            db.closeCon();
        } catch (SQLException ex) {
            Logger.getLogger(VCars.class.getName()).log(Level.SEVERE, null, ex);
        }
        setResults();
    }//GEN-LAST:event_searchBtnActionPerformed

    private void nextBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextBtnActionPerformed
        current++;
        setResults();
    }//GEN-LAST:event_nextBtnActionPerformed

    private void prevBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prevBtnActionPerformed
        current--;
        setResults();
    }//GEN-LAST:event_prevBtnActionPerformed

    private void closeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBtnActionPerformed
        new GuestView().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_closeBtnActionPerformed
  private void setResults(){
        
        if(!(selectedCars.isEmpty()) & current==0 & selectedCars.size()==1){
            prevBtn.setVisible(true);
            nextBtn.setVisible(true);
            imgLbl.setVisible(true);
            prevBtn.setEnabled(false);
            nextBtn.setEnabled(false);
            jLabel4.setText(selectedCars.get(current).toString());
            imgLbl.setIcon(new ImageIcon(getClass().getResource("/media/"+carIDs.get(current)+".png")));
        }else if(!(selectedCars.isEmpty()) & current==0 & selectedCars.size()>1){
            prevBtn.setVisible(true);
            nextBtn.setVisible(true);
            imgLbl.setVisible(true);
            prevBtn.setEnabled(false);
            nextBtn.setEnabled(true);
            jLabel4.setText(selectedCars.get(current).toString());
            imgLbl.setIcon(new ImageIcon(getClass().getResource("/media/"+carIDs.get(current)+".png")));
        }else if(!(selectedCars.isEmpty()) & current ==(selectedCars.size()-1)){
            prevBtn.setVisible(true);
            nextBtn.setVisible(true);
            imgLbl.setVisible(true);
            nextBtn.setEnabled(false);
            prevBtn.setEnabled(true);
            jLabel4.setText(selectedCars.get(current).toString());
            imgLbl.setIcon(new ImageIcon(getClass().getResource("/media/"+carIDs.get(current)+".png")));
        }else if(!(selectedCars.isEmpty())){
            prevBtn.setVisible(true);
            nextBtn.setVisible(true);
            imgLbl.setVisible(true);
            prevBtn.setEnabled(true);
            nextBtn.setEnabled(true);
            jLabel4.setText(selectedCars.get(current).toString());
            imgLbl.setIcon(new ImageIcon(getClass().getResource("/media/"+carIDs.get(current)+".png")));
        }else if(selectedCars.isEmpty()){
            JOptionPane.showMessageDialog(null, "No cars found. Please choose a category, type the number of seats and try again!");
        }
        
        
        
       
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VCars.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VCars.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VCars.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VCars.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VCars().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cTypeCmb;
    private javax.swing.JButton closeBtn;
    private javax.swing.JLabel imgLbl;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton nextBtn;
    private javax.swing.JTextField noOfSeatTxt;
    private javax.swing.JButton prevBtn;
    private javax.swing.JButton searchBtn;
    private javax.swing.JLabel seatsLbl;
    private javax.swing.JLabel titleLbl;
    private javax.swing.JLabel typeLbl;
    // End of variables declaration//GEN-END:variables
}
