/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package report;

import UIPkg.LogInScreen;
import java.util.HashMap;

/**
 *
 * @author Ihsan Izwer
 */
public class ViewReports extends javax.swing.JFrame {

    /**
     * Creates new form ViewReports
     */
    public ViewReports() {
        initComponents();
        this.setSize(820, 512);
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        closeBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        carReportButton = new javax.swing.JButton();
        userReportButton = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        orderReportBtn = new javax.swing.JButton();
        customerReportBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        closeBtn.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        closeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/icons/x-mark-32.png"))); // NOI18N
        closeBtn.setText("Close");
        closeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBtnActionPerformed(evt);
            }
        });
        getContentPane().add(closeBtn);
        closeBtn.setBounds(670, 20, 120, 40);

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel2.setText("View Reports");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 20, 160, 50);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(490, 110, 170, 30);

        jTextField2.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        getContentPane().add(jTextField2);
        jTextField2.setBounds(520, 200, 140, 30);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(510, 290, 150, 30);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(510, 370, 150, 30);

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel5.setText("Enter order delivery date :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(280, 290, 230, 26);

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel3.setText("Enter type of user:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(320, 100, 170, 50);

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel4.setText("Enter number of seats:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(320, 200, 200, 30);

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel6.setText("Enter customer name :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(320, 370, 190, 30);

        jButton8.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jButton8.setText("View");
        getContentPane().add(jButton8);
        jButton8.setBounds(700, 370, 100, 30);

        jButton6.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jButton6.setText("View");
        getContentPane().add(jButton6);
        jButton6.setBounds(700, 200, 100, 30);

        jButton5.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jButton5.setText("View");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(703, 110, 100, 30);

        carReportButton.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        carReportButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/icons/car32.png"))); // NOI18N
        carReportButton.setText("View all Cars");
        carReportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carReportButtonActionPerformed(evt);
            }
        });
        getContentPane().add(carReportButton);
        carReportButton.setBounds(40, 180, 200, 60);

        userReportButton.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        userReportButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/icons/Material Icons_e8a3(1)_32.png"))); // NOI18N
        userReportButton.setText("View all Users");
        userReportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userReportButtonActionPerformed(evt);
            }
        });
        getContentPane().add(userReportButton);
        userReportButton.setBounds(40, 270, 200, 60);

        jButton7.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jButton7.setText("View");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(700, 290, 100, 30);

        orderReportBtn.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        orderReportBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/icons/order 32.png"))); // NOI18N
        orderReportBtn.setText("View all Orders");
        orderReportBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderReportBtnActionPerformed(evt);
            }
        });
        getContentPane().add(orderReportBtn);
        orderReportBtn.setBounds(40, 90, 200, 60);

        customerReportBtn.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        customerReportBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/icons/customer32.png"))); // NOI18N
        customerReportBtn.setText("View all Customers");
        customerReportBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerReportBtnActionPerformed(evt);
            }
        });
        getContentPane().add(customerReportBtn);
        customerReportBtn.setBounds(40, 360, 230, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/bac.jpeg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(4, -6, 820, 520);

        setBounds(0, 0, 836, 551);
    }// </editor-fold>//GEN-END:initComponents

    private void closeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBtnActionPerformed
        new LogInScreen().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_closeBtnActionPerformed

    private void carReportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carReportButtonActionPerformed
        RView r = new RView("C:\\Users\\Ihsan Izwer\\Documents\\NetBeansProjects\\ABC\\src\\report\\car.jasper");
        r.setVisible(true);
    }//GEN-LAST:event_carReportButtonActionPerformed

    private void customerReportBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerReportBtnActionPerformed
        RView r = new RView("C:\\Users\\Ihsan Izwer\\Documents\\NetBeansProjects\\ABC\\src\\report\\Customer.jasper");
        r.setVisible(true);
    }//GEN-LAST:event_customerReportBtnActionPerformed

    private void orderReportBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderReportBtnActionPerformed
        RView r = new RView("C:\\Users\\Ihsan Izwer\\Documents\\NetBeansProjects\\ABC\\src\\report\\Order.jasper");
        r.setVisible(true);
    }//GEN-LAST:event_orderReportBtnActionPerformed

    private void userReportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userReportButtonActionPerformed
        RView r = new RView("C:\\Users\\Ihsan Izwer\\Documents\\NetBeansProjects\\ABC\\src\\report\\Users.jasper");
        r.setVisible(true);
    }//GEN-LAST:event_userReportButtonActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if(!(jTextField1.getText().length()==0)){
            HashMap para = new HashMap();
            para.put("receptionist", jTextField1.getText());
            RView r = new RView("C:\\Users\\Ihsan Izwer\\Documents\\NetBeansProjects\\ABC\\src\\report\\Users_para.jasper", para);
            r.setVisible(true);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
         if(!(jTextField3.getText().length()==0)){
            HashMap para = new HashMap();
            para.put("2017/05/02", jTextField3.getText());
            RView r = new RView("C:\\Users\\Ihsan Izwer\\Documents\\NetBeansProjects\\ABC\\src\\report\\Order_Parameterized.jasper", para);
            r.setVisible(true);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewReports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewReports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewReports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewReports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewReports().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton carReportButton;
    private javax.swing.JButton closeBtn;
    private javax.swing.JButton customerReportBtn;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JButton orderReportBtn;
    private javax.swing.JButton userReportButton;
    // End of variables declaration//GEN-END:variables
}
