/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces1;

import classes.*;
import java.util.Date;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import java.sql.*;

/**
 *
 * @author Kashif Roshen
 */
public class addOrder extends javax.swing.JFrame {

    /**
     * Creates new form addOrder
     */
    public addOrder() {
        initComponents();
        group();
        Disable();
        
        Connection con=DBconnection.connect();
        
        try
        {
            Statement statement=con.createStatement();

            String query="SELECT * FROM car";
            
            Model.setEnabled(false);

            ResultSet x=statement.executeQuery(query);

                while (x.next())
                {
                    Make.addItem(x.getString("Make"));
                }
                
        }    
        
        
        catch(Exception e)
        {
            System.out.println(e);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        O_by_time = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        car_name = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        t_delivered_day = new javax.swing.JComboBox<>();
        t_delivered_year = new javax.swing.JComboBox<>();
        t_delivered_month = new javax.swing.JComboBox<>();
        t_delivered_hour = new javax.swing.JComboBox<>();
        t_delivered_minute = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        t_return_hour = new javax.swing.JComboBox<>();
        t_return_minute = new javax.swing.JComboBox<>();
        O_by_day = new javax.swing.JRadioButton();
        d_delivered_day = new javax.swing.JComboBox<>();
        d_delivered_month = new javax.swing.JComboBox<>();
        d_delivered_year = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        d_return_day = new javax.swing.JComboBox<>();
        d_return_month = new javax.swing.JComboBox<>();
        d_return_year = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        Model = new javax.swing.JComboBox<>();
        Make = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        cus_name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel2.setPreferredSize(new java.awt.Dimension(820, 512));
        jPanel2.setLayout(null);

        O_by_time.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        O_by_time.setText("Order by time");
        O_by_time.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                O_by_timeActionPerformed(evt);
            }
        });
        jPanel2.add(O_by_time);
        O_by_time.setBounds(380, 100, 130, 29);

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel4.setText("Delivered day   :");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(380, 140, 110, 30);

        car_name.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        car_name.setText("Select Car          :");
        jPanel2.add(car_name);
        car_name.setBounds(30, 220, 120, 30);

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel5.setText("Delivered time :");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(380, 180, 110, 20);

        t_delivered_day.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        t_delivered_day.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "day", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        t_delivered_day.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_delivered_dayActionPerformed(evt);
            }
        });
        jPanel2.add(t_delivered_day);
        t_delivered_day.setBounds(500, 140, 60, 27);

        t_delivered_year.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        t_delivered_year.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "year", "2016", "2017", "2018", "2019", "2020" }));
        t_delivered_year.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_delivered_yearActionPerformed(evt);
            }
        });
        jPanel2.add(t_delivered_year);
        t_delivered_year.setBounds(660, 140, 70, 27);

        t_delivered_month.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        t_delivered_month.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "month", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        jPanel2.add(t_delivered_month);
        t_delivered_month.setBounds(570, 140, 80, 27);

        t_delivered_hour.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        t_delivered_hour.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "hour", "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", " " }));
        jPanel2.add(t_delivered_hour);
        t_delivered_hour.setBounds(500, 180, 60, 27);

        t_delivered_minute.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        t_delivered_minute.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "minute", "00", "30" }));
        jPanel2.add(t_delivered_minute);
        t_delivered_minute.setBounds(570, 180, 80, 27);

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel6.setText("Return time      :");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(380, 220, 120, 20);

        t_return_hour.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        t_return_hour.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "hour", "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", " " }));
        jPanel2.add(t_return_hour);
        t_return_hour.setBounds(500, 220, 60, 27);

        t_return_minute.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        t_return_minute.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "minute", "00", "30" }));
        jPanel2.add(t_return_minute);
        t_return_minute.setBounds(570, 220, 80, 27);

        O_by_day.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        O_by_day.setText("Order by day");
        O_by_day.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                O_by_dayActionPerformed(evt);
            }
        });
        jPanel2.add(O_by_day);
        O_by_day.setBounds(380, 260, 120, 29);

        d_delivered_day.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        d_delivered_day.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "day", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jPanel2.add(d_delivered_day);
        d_delivered_day.setBounds(500, 300, 60, 27);

        d_delivered_month.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        d_delivered_month.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "month", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        jPanel2.add(d_delivered_month);
        d_delivered_month.setBounds(570, 300, 80, 27);

        d_delivered_year.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        d_delivered_year.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "year", "2016", "2017", "2018", "2019", "2020" }));
        jPanel2.add(d_delivered_year);
        d_delivered_year.setBounds(660, 300, 70, 27);

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel7.setText("Delivered day   :");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(380, 300, 130, 30);

        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel8.setText("Return day        :");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(380, 340, 110, 30);

        d_return_day.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        d_return_day.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "day", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jPanel2.add(d_return_day);
        d_return_day.setBounds(500, 340, 60, 27);

        d_return_month.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        d_return_month.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "month", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        jPanel2.add(d_return_month);
        d_return_month.setBounds(570, 340, 80, 27);

        d_return_year.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        d_return_year.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "year", "2016", "2017", "2018", "2019", "2020" }));
        jPanel2.add(d_return_year);
        d_return_year.setBounds(660, 340, 70, 27);

        jButton2.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jButton2.setText("OK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(160, 270, 70, 35);

        jButton3.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jButton3.setText("OK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);
        jButton3.setBounds(500, 380, 80, 35);

        Model.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        Model.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Model" }));
        jPanel2.add(Model);
        Model.setBounds(250, 220, 80, 27);

        Make.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        Make.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Make" }));
        Make.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MakeActionPerformed(evt);
            }
        });
        jPanel2.add(Make);
        Make.setBounds(160, 220, 80, 27);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel1.setText("Customer Name  :");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(30, 160, 130, 30);

        cus_name.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jPanel2.add(cus_name);
        cus_name.setBounds(160, 160, 170, 30);

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel3.setText("    ADD ORDER");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(110, 100, 180, 26);

        jButton5.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/icons/home.png"))); // NOI18N
        jButton5.setText("Home");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5);
        jButton5.setBounds(660, 20, 120, 41);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/bac.jpeg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.setPreferredSize(new java.awt.Dimension(820, 513));
        jPanel2.add(jLabel2);
        jLabel2.setBounds(0, -10, 830, 520);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 820, 512);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void Disable()
    {
         d_delivered_day.setEnabled(false);
        d_delivered_month.setEnabled(false);
        d_delivered_year.setEnabled(false);
        d_return_day.setEnabled(false);
        d_return_month.setEnabled(false);
        d_return_year.setEnabled(false);
        
        t_delivered_day.setEnabled(false);
        t_delivered_hour.setEnabled(false);
        t_delivered_minute.setEnabled(false);
        t_delivered_month.setEnabled(false);
        t_delivered_year.setEnabled(false);
        t_return_hour.setEnabled(false);
        t_return_minute.setEnabled(false);
        
        O_by_day.setEnabled(false);
        O_by_time.setEnabled(false);
    }
    
    private void Enable()
    {
        
        
        d_delivered_day.setEnabled(true);
        d_delivered_month.setEnabled(true);
        d_delivered_year.setEnabled(true);
        d_return_day.setEnabled(true);
        d_return_month.setEnabled(true);
        d_return_year.setEnabled(true);
        
        t_delivered_day.setEnabled(true);
        t_delivered_hour.setEnabled(true);
        t_delivered_minute.setEnabled(true);
        t_delivered_month.setEnabled(true);
        t_delivered_year.setEnabled(true);
        t_return_hour.setEnabled(true);
        t_return_minute.setEnabled(true);
        
        O_by_day.setEnabled(true);
        O_by_time.setEnabled(true);
    }
    private void O_by_timeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_O_by_timeActionPerformed
        d_delivered_day.setEnabled(false);
        d_delivered_month.setEnabled(false);
        d_delivered_year.setEnabled(false);
        d_return_day.setEnabled(false);
        d_return_month.setEnabled(false);
        d_return_year.setEnabled(false);
        
        t_delivered_day.setEnabled(true);
        t_delivered_hour.setEnabled(true);
        t_delivered_minute.setEnabled(true);
        t_delivered_month.setEnabled(true);
        t_delivered_year.setEnabled(true);
        t_return_hour.setEnabled(true);
        t_return_minute.setEnabled(true);
        
    }//GEN-LAST:event_O_by_timeActionPerformed

    private void t_delivered_yearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_delivered_yearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_delivered_yearActionPerformed

    private void t_delivered_dayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_delivered_dayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_delivered_dayActionPerformed

    private void O_by_dayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_O_by_dayActionPerformed
         d_delivered_day.setEnabled(true);
        d_delivered_month.setEnabled(true);
        d_delivered_year.setEnabled(true);
        d_return_day.setEnabled(true);
        d_return_month.setEnabled(true);
        d_return_year.setEnabled(true);
        
        t_delivered_day.setEnabled(false);
        t_delivered_hour.setEnabled(false);
        t_delivered_minute.setEnabled(false);
        t_delivered_month.setEnabled(false);
        t_delivered_year.setEnabled(false);
        t_return_hour.setEnabled(false);
        t_return_minute.setEnabled(false);
    }//GEN-LAST:event_O_by_dayActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
       
        Add_Order order=new Add_Order();
        
        String Customer_name=cus_name.getText();
        
        String selectedMake = Make.getSelectedItem().toString();
        
        String selectedModel = Model.getSelectedItem().toString();
        
        boolean check1=order.CheckCustomer(Customer_name);
        boolean check2=order.checkCar(selectedMake, selectedModel);
        
        if (check1==false)
        {
            JOptionPane.showMessageDialog(null,"Customer does not exist");
        }
        
        else if (check2==true)
        {
            JOptionPane.showMessageDialog(null,"Car is not available");
        }
        
        else
        {
           Enable();  
        }
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
         Add_Order order1=new Add_Order();
          String Customer_name=cus_name.getText();
        
        String selectedMake = Make.getSelectedItem().toString();
        
        String selectedModel = Model.getSelectedItem().toString();
        
        if (O_by_day.isSelected())
        {
            String delivered_day=d_delivered_day.getSelectedItem().toString();
            String delivered_month=d_delivered_month.getSelectedItem().toString();
            String delivered_year=d_delivered_year.getSelectedItem().toString();
            
            Date Delivered_day=ValidateDateorTime.ConvertStringtoDate(delivered_year,delivered_month,delivered_day);
            
            
            String return_day=d_return_day.getSelectedItem().toString();
            String return_month=d_return_month.getSelectedItem().toString();
            String return_year=d_return_year.getSelectedItem().toString();
            
            Date Returned_day=ValidateDateorTime.ConvertStringtoDate(return_year,return_month,return_day);
           
            
            ValidateDateorTime validate=new ValidateDateorTime();
            
            validate.setDates(Delivered_day,Returned_day);
            
            boolean validate_result=validate.validateDates();
            
            if ( validate_result==false)
            {
                JOptionPane.showMessageDialog(null,"Invalid date");
            }
            
            else
            {
                order1.RetrievePrice(selectedModel,selectedMake);
                order1.CalculateAmount(delivered_year, delivered_month, delivered_day, return_year, return_month, return_day);
                order1.insertFinalValues();
                order1.AddRentRecord(Customer_name);
            }
        }
         
         if (O_by_time.isSelected())
        {
            String delivered_day=t_delivered_day.getSelectedItem().toString();
            String delivered_month=t_delivered_month.getSelectedItem().toString();
            String delivered_year=t_delivered_year.getSelectedItem().toString();
            
            String delivered_date=delivered_year+"/"+delivered_month+"/"+delivered_day;
            
            String delivered_hour=t_delivered_hour.getSelectedItem().toString();
            String delivered_minute=t_delivered_minute.getSelectedItem().toString();
            
            Date Delivered_time=ValidateDateorTime.convertStringtoTime(delivered_year,delivered_month,delivered_day,delivered_hour,delivered_minute);
            
            String returned_hour=t_return_hour.getSelectedItem().toString();
            String returned_minute=t_return_minute.getSelectedItem().toString();
            
            Date Return_time=ValidateDateorTime.convertStringtoTime(delivered_year,delivered_month,delivered_day,returned_hour,returned_minute);
            
            ValidateDateorTime validate=new ValidateDateorTime();
            
            validate.setTimes(Delivered_time,Return_time);
            
            boolean validate_result=validate.validateTime();
            
            if (validate_result==false)
            {
                JOptionPane.showMessageDialog(null,"Invalid date");
            }
            
            else 
            {
                order1.RetrievePrice(selectedModel,selectedMake);
                order1.CalculateAmount(delivered_date, delivered_hour, delivered_minute, returned_hour, returned_minute);
                order1.insertFinalValues();
                order1.AddRentRecord(Customer_name);
            }
            
            
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
         main window=new main();
        window.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void MakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MakeActionPerformed
        
        String selectedMake = Make.getSelectedItem().toString();
        
        Model.setEnabled(true);
        
        try
        {
            Connection conM=DBconnection.connect();
            
            Statement st=conM.createStatement();
            
            String getModel="SELECT Model FROM car WHERE Make='"+selectedMake+"'";
            
            ResultSet rs=st.executeQuery(getModel);
            
            while (rs.next())
            {
                 Model.addItem(rs.getString("Model"));
            }
        }
            catch(Exception e)
            {
              System.out.println(e);  
            }
        
    }//GEN-LAST:event_MakeActionPerformed
    
    private void group()
    {
        ButtonGroup group=new ButtonGroup();
        
        group.add(O_by_time);
        group.add(O_by_day);
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addOrder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Make;
    private javax.swing.JComboBox<String> Model;
    private javax.swing.JRadioButton O_by_day;
    private javax.swing.JRadioButton O_by_time;
    private javax.swing.JLabel car_name;
    private javax.swing.JTextField cus_name;
    private javax.swing.JComboBox<String> d_delivered_day;
    private javax.swing.JComboBox<String> d_delivered_month;
    private javax.swing.JComboBox<String> d_delivered_year;
    private javax.swing.JComboBox<String> d_return_day;
    private javax.swing.JComboBox<String> d_return_month;
    private javax.swing.JComboBox<String> d_return_year;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox<String> t_delivered_day;
    private javax.swing.JComboBox<String> t_delivered_hour;
    private javax.swing.JComboBox<String> t_delivered_minute;
    private javax.swing.JComboBox<String> t_delivered_month;
    private javax.swing.JComboBox<String> t_delivered_year;
    private javax.swing.JComboBox<String> t_return_hour;
    private javax.swing.JComboBox<String> t_return_minute;
    // End of variables declaration//GEN-END:variables
}
